README.md
maestro

Add dependencies to readme

---

Communicator.py
README.md
config/orion.yaml
maestro

Update README with syntax examples

Configuration support for ldmsd sampler's

---

Communicator.py
README.md
config/orion.yaml
maestro
maestro_ctrl

Split maestro into 2 commands.
Update sampling intervals with maestro

Refactor maestro monitoring code

---

README.md
config/orion.yaml
maestro
maestro_ctrl

Change "hosts" vernacular in ldms cluster yaml config to "endpoints".
Add group description in ldms cluster yaml config

LDMS Cluster Configuration generator for maestro_ctrl

---

maestro_ctrl

Includes flush configuration parameter for lsos deployments and the "plugin" yaml entry for plugin configuration not unique to samplers, producers, or aggregators.

Stores flush

---

maestro
maestro_ctrl

Add proper parsing for ovis authentication

Hotfix for ldmsd "ovis" authentication method

---

Communicator.py
config/mult_auth.conf
config/orion.yaml
maestro
maestro_ctrl

add example template for multi authentication
integer handling for cvt_intrvl_to_us
mult_auth support for config generation
remove deprecated options from orion.yaml

support for multiple authentication domains within a cluster

---

Communicator.py
maestro
maestro_ctrl

Error handling for yaml keys with forward slash
Various bug fixes/code consolidation

Support for multi-endpoint listening

---

Communicator.py
maestro
maestro_ctrl

Feature - Load balancing by metric sets or by producers with --rebalance <balance_opt>. defaults to "producers"
added updtr_status and dir_list methods to communicator
aggregator dict set programmatically, rather than cloning etcd
agg dict stores current sets it is aggregating when load balancing by set
ldmsd_state organized by group

Smplr set balancing

---

scripts/maestro
src/maestro/Communicator.py

Include exception message in Communicator method responses

Improved Communicator error logging

---

scripts/maestro_ctrl

combine write_dmn_producers and write_producers into single method

Update local mode and config v4 producer balancing logic

---

scripts/maestro_ctrl
src/maestro/maestro_util.py

Check that each key's types are appropriate before performing
operations, and issue an error with an example of appropriate syntax
otherwise

Improved yaml parsing for ldms_config file

---

scripts/maestro
src/maestro/Communicator.py

Add 'tconnect' communicator method that adds connection timeout to ldms xprt
Create separate function to add streams after producers have been started

LDMS connection timeout

---

scripts/maestro

streams_cntr

---

scripts/maestro

Add type checking for updtr_status in add_updaters

Type check message response from updtr_status

---

scripts/maestro

Ensure metric sets are aggregated appropriately when rebalancing with metric set load

Rebalance based on aggregation levels

---

scripts/maestro
scripts/maestro_ctrl
src/maestro/maestro_util.py

Function fmt_cmd_args added to maestro_util to parse ldmsd command arguments

Add decomposition support to maestro

---

scripts/maestro_ctrl
src/maestro/maestro_util.py

Implement function to check that format is correct for time strings
Add debug option to maestro_ctrl "--debug"

Remove formatting from maestro_ctrl

---

README.md
config/example_config.yaml
scripts/maestro
scripts/maestro_ctrl
src/maestro/maestro_util.py

Support for data rate clamping of transports and streams
Support for configuration of ZAP RAIL on streams and producers

Rails, rate limiting, and credit support

---

README.md
scripts/maestro
scripts/maestro_ctrl
setup.cfg
src/maestro/maestro_raft.py
src/maestro/maestro_util.py

New feature Multi-Instance Maestro
Allows Maestro to run in a cluster with at least 3 other Maestro daemons, and distribute LDMS cluster load balancing, monitoring, and configuration responsibilities among Maestro cluster members.

Multi instance maestro

---

README.md
config/example_advertiser_config.yaml
scripts/maestro
scripts/maestro_ctrl
setup.cfg
src/maestro/maestro_util.py

Adds support for advertisers and producer listeners to Maestro

Advertisers

---

scripts/maestro
scripts/maestro_ctrl

Syntax fix when checking if producer is a list

Local mode "local" argument

---

README.md
scripts/maestro
scripts/maestro_ctrl
src/maestro/maestro_raft.py

Adds support for multi-instance plugins

Multi instance

---

scripts/maestro

Correctly stop plugins on samplers when reconfiguring.

Bug fix for stop_samplers function
